apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: document-intelligence
resources:
  - namespace.yaml
  - configmap.yaml
  - migration-job.yaml
  - api-deployment.yaml
  - api-service.yaml
  - worker-deployment.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
